#!/bin/sh

# Linking up stuff
ln -s ~/.dotfiles/vim/ ~/.vim
ln -s ~/.dotfiles/bashrc ~/.bashrc
ln -s ~/.dotfiles/vimrc ~/.vimrc
ln -s ~/.dotfiles/vim/jslintrc ~/.jslintrc

# Setting up git submodules
git submodule init
git submodule update
