# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=154890&PersonId=136290&CustomerId=124&Guid=68b9cf24bb7e571bb2f309637ee16596&Culture=nb-NO", tags=["1STD Engelsk"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=155047&PersonId=136290&CustomerId=124&Guid=1060b94f54a357ac470717a6f791e6e8&Culture=nb-NO", tags=["1STD Tysk II"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=154890&PersonId=136290&CustomerId=124&Guid=68b9cf24bb7e571bb2f309637ee16596&Culture=nb-NO", tags=["1STD Engelsk"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=154872&PersonId=136290&CustomerId=124&Guid=77758ed803cec4361310cc775e9001d5&Culture=nb-NO", tags=["1STD Geografi"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=154878&PersonId=136290&CustomerId=124&Guid=dddd40dc795424a40554105b0baef730&Culture=nb-NO", tags=["1STD Kroppsøving"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=154866&PersonId=136290&CustomerId=124&Guid=5edc7096984bd8263d72255283b00b9f&Culture=nb-NO", tags=["1STD Naturfag"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=154859&PersonId=136290&CustomerId=124&Guid=02ad1081040fd4ac8897a4e616fb2674&Culture=nb-NO", tags=["1STD Norsk hovedmål, skriftlig"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=154852&PersonId=136290&CustomerId=124&Guid=034741723bd971bc2b12fb964ddc6d3a&Culture=nb-NO", tags=["1STD Norsk, muntlig"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=154844&PersonId=136290&CustomerId=124&Guid=3dc331270f6732b0a9b591cd78603c4a&Culture=nb-NO", tags=["1STD Samfunnsfag"])
add("https://www.itslearning.com/Bulletin/RssFeed.aspx?LocationType=1&LocationID=155047&PersonId=136290&CustomerId=124&Guid=1060b94f54a357ac470717a6f791e6e8&Culture=nb-NO", tags=["1STD Tysk II"])


link_handler("firefox \"%u\"")
