# LOADING IN THE DIFFRENT THINGS!
autoload -U compinit promptinit
autoload -U colors && colors
compinit
promptinit

# = VARIABLES =
PATH=/usr/local/bin/:$PATH:$HOME/scripts:$HOME/bin:$HOME/bin/depot_tools/
export PATH

# Editorz!
export EDITOR="vim"
export VISAUL=$EDITOR
export ALTERNATE_EDITOR=""

# Settting the terminal
export TERM=xterm-256color

# no bleeps
setopt NOBEEP 
# =Logging=
export HISTSIZE=1000        # Number of lines kept in history
export SAVEHIST=1000        # number of lines saved in the history after logout
export HISTFILE=~/.zhistory
setopt share_history        # Logging across shells
setopt inc_append_history   # Logging across shells

# Resource files
for file in $HOME/.zsh/rc/*.rc; do
    source $file
done
